[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/qr-redirect"
  to = "/qr-redirect.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true